repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: uv run ruff check --fix
        language: system
        types: [python]

      - id: fmt
        name: format
        entry: uv run ruff format
        language: system
        types: [python]

      - id: tc
        name: type-check
        entry: uv run mypy .
        language: system
        types: [python]
        pass_filenames: false
